import {
  IoAmericanFootballOutline,
  IoBagCheckOutline,
  IoBuildOutline,
  IoHappyOutline,
  IoRocketOutline,
  IoWatchOutline,
} from "react-icons/io5";

import { HiOutlineDeviceTablet } from "react-icons/hi";

import {
  CalendarIcon,
  ChartPieIcon,
  DocumentDuplicateIcon,
  FolderIcon,
  HomeIcon,
} from "@heroicons/react/24/outline";

const navigation = [
  { name: "Dashboard", href: "admin/", icon: HomeIcon, current: true },
  { name: "Product", href: "admin/product", icon: FolderIcon, current: false },
  {
    name: "Attributes",
    href: "admin/attributes",
    icon: DocumentDuplicateIcon,
    current: false,
  },
  {
    name: "Category",
    href: "admin/category",
    icon: ChartPieIcon,
    current: false,
  },
  { name: "Order", href: "admin/order", icon: FolderIcon, current: false },
  { name: "Coupon", href: "admin/coupon", icon: CalendarIcon, current: false },
  {
    name: "Our Staff",
    href: "admin/staff",
    icon: DocumentDuplicateIcon,
    current: false,
  },
  {
    name: "View Store",
    href: "admin/view-store",
    icon: DocumentDuplicateIcon,
    current: false,
  },
  {
    name: "Store Customization",
    href: "admin/store-customization",
    icon: DocumentDuplicateIcon,
    current: false,
  },
];

export const menuItems = [
  {
    name: "Home",
    href: "/",
  },
  {
    name: "Products",
    href: "/products",
  },
  {
    name: "Coupons",
    href: "/coupons",
  },
  {
    name: "Pages",
    submenu: [
      { name: "About Us", href: "/about" },
      { name: "Contact", href: "/contact" },
      { name: "Blogs", href: "/blog-listing" },
      { name: "Terms & Condition", href: "/terms-condition" },
    ],
  },
];

const categorys = [
  { id: 1, name: "Laptop" },
  { id: 2, name: "Phone" },
  { id: 3, name: "Tools" },
  { id: 4, name: "Smart watch" },
];

const userNavigation = [
  { name: "Your profile", href: "#" },
  { name: "Sign out", href: "#" },
];

const topCategory = [
  {
    id: 1,
    icon: IoAmericanFootballOutline,
    title: "Outdoor & Sports",
    item: "150",
  },
  {
    id: 2,
    icon: IoHappyOutline,
    title: "Kids & Babies",
    item: "250",
  },
  {
    id: 3,
    icon: IoBagCheckOutline,
    title: "Bags & Luggage",
    item: 200,
  },
  {
    id: 4,
    icon: IoHappyOutline,
    title: "Women's Fashion",
    item: 100,
  },
  {
    id: 5,
    icon: IoHappyOutline,
    title: "Hair Products",
    item: 300,
  },
  {
    id: 6,
    icon: IoHappyOutline,
    title: "Men's Fashion",
    item: 300,
  },
  {
    id: 7,
    icon: IoHappyOutline,
    title: "Office Supplies",
    item: 350,
  },
  {
    id: 8,
    icon: HiOutlineDeviceTablet,
    title: "Phones & Tablets",
    item: 450,
  },
  {
    id: 9,
    icon: IoHappyOutline,
    title: "Jewelry Eyeweare",
    item: 400,
  },
  {
    id: 10,
    icon: IoWatchOutline,
    title: "Smart Watch",
    item: 500,
  },
  {
    id: 11,
    icon: IoHappyOutline,
    title: "Shoes & Footwear",
    item: 450,
  },
  {
    id: 12,
    icon: IoRocketOutline,
    title: "Toys & Games",
    item: 350,
  },
  {
    id: 14,
    icon: IoHappyOutline,
    title: "Beauty & Health",
    item: 450,
  },
  {
    id: 15,
    icon: IoHappyOutline,
    title: "Automobiles Parts",
    item: 400,
  },
  {
    id: 16,
    icon: IoHappyOutline,
    title: "Home Appliance",
    item: 550,
  },
  {
    id: 17,
    icon: IoBuildOutline,
    title: "Tools & Hardware",
    item: 450,
  },
];

const blogGrideData = [
  {
    id: 1,
    image: "/img/blog/4.jpg",
    title: "30 Product Management thought Leaders to follow",
    des: "Compellingly morph proactive niches without fully researched quality vectors build long-term high-impact.",
    owenr: { name: "Tahlia Rickard", avatar: "/img/avatars/10.jpg" },
  },
  {
    id: 2,
    image: "/img/blog/5.jpg",
    title: "4 Steps for Measuring the Impact of product Discovery. Watch Video",
    des: "Appropriately cultivate clicks-and-mortar action items and parallel intellectual maintain goal-oriented intellectual.",
    owenr: { name: "Hannah Halloran", avatar: "/img/avatars/9.jpg" },
  },
  {
    id: 3,
    image: "/img/blog/6.jpg",
    title: "Digital Product Management tools and Tech",
    owenr: { name: "Justin Hurley", avatar: "/img/avatars/8.jpg" },
    des: "Holisticly administrate future-proof niche markets without frictionless collaboration and idea-sharing.",
  },
  {
    id: 4,
    image: "/img/blog/7.jpg",
    title: "Top 10 Trends High Quality Fashion in World 2022",
    owenr: { name: "Justin Hurley", avatar: "/img/avatars/3.jpg" },
    des: "Quickly develop open-source internal professionally empower premium action items before revolutionary benefits",
  },
  {
    id: 5,
    image: "/img/blog/8.jpg",
    title: "Digital Product Management tools and Tech",
    owenr: { name: "Justin Hurley", avatar: "/img/avatars/4.jpg" },
    des: "Holisticly administrate future-proof niche markets without frictionless collaboration and idea-sharing.",
  },
  {
    id: 6,
    image: "/img/blog/10.jpg",
    title: "The Modern product Manager’s Tech stack",
    owenr: { name: "Lucy Murnin", avatar: "/img/avatars/5.jpg" },
    des: "Conveniently monetize orthogonal internal or organic sources rather than parallel Professionally redefine.",
  },
  {
    id: 7,
    image: "/img/blog/11.jpg",
    title: "4 Steps for Measuring the Impact of product Discovery. Watch Video",
    owenr: { name: " Hannah Halloran", avatar: "/img/avatars/6.jpg" },
    des: "Appropriately cultivate clicks-and-mortar action items and parallel intellectual maintain goal-oriented intellectual capital",
  },
  {
    id: 8,
    image: "/img/blog/12.jpg",
    title: "Digital Product Management tools and Tech",
    owenr: { name: "Justin Hurley", avatar: "/img/avatars/7.jpg" },
    des: "Holisticly administrate future-proof niche markets without frictionless collaboration and idea-sharin",
  },
];

const discountSliderProducts = [
  {
    id: 1,
    image: "/img/products/featured/1.jpg",
    price: 150,
    originalPrice: 200,
  },
  {
    id: 2,
    image: "/img/products/featured/2.jpg",
    price: 350,
    originalPrice: 400,
  },
  {
    id: 3,
    image: "/img/products/featured/3.jpg",
    price: 250,
    originalPrice: 300,
  },
  {
    id: 4,
    image: "/img/products/featured/4.jpg",
    price: 300,
    originalPrice: 360,
  },
  {
    id: 5,
    image: "/img/products/featured/5.jpg",
    price: 200,
    originalPrice: 250,
  },
  {
    id: 6,
    image: "/img/products/featured/6.jpg",
    price: 150,
    originalPrice: 200,
  },
  {
    id: 7,
    image: "/img/products/featured/7.jpg",
    price: 400,
    originalPrice: 450,
  },
  {
    id: 8,
    image: "/img/products/featured/8.jpg",
    price: 350,
    originalPrice: 400,
  },
  {
    id: 9,
    image: "/img/products/featured/9.jpg",
    price: 250,
    originalPrice: 300,
  },
  {
    id: 10,
    image: "/img/products/featured/10.jpg",
    price: 150,
    originalPrice: 200,
  },
];

const flashSaleSliderProducts = [
  {
    id: 1,
    title: "Men's Orange Black White Print Summer Sweater",
    image: "/img/products/electronic-fabric/9.jpg",
    price: 150,
    originalPrice: 200,
    discount: 20,
    review: 50,
    sale: 200,
  },
  {
    id: 2,
    title: "Rainbow Jacquard Sweater for Women",
    image: "/img/products/electronic-fabric/13.jpg",
    price: 350,
    originalPrice: 400,
    discount: 50,
    review: 100,
    sale: 350,
  },
  {
    id: 3,
    title: "Bluetooth Wireless 5.0 Smart Watch",
    image: "/img/products/electronic-fabric/10.jpg",
    price: 250,
    originalPrice: 300,
    discount: 60,
    review: 350,
    sale: 1000,
  },
  {
    id: 4,
    title: "Apple 2022 Macbook Pro 18GB 256GB Laptop",
    image: "/img/products/electronic-fabric/4.jpg",
    price: 300,
    originalPrice: 360,
    discount: 40,
    review: 200,
    sale: 300,
  },
  {
    id: 5,
    title: "Women Sweaters Autumn Winter Tops Slim Women",
    image: "/img/products/electronic-fabric/12.jpg",
    price: 200,
    originalPrice: 250,
    discount: 50,
    review: 400,
    sale: 1000,
  },
  {
    id: 6,
    title: "Multicolor Rainbow Jacquard Sweater for Women",
    image: "/img/products/electronic-fabric/14.jpg",
    price: 150,
    originalPrice: 200,
    discount: 70,
    review: 200,
    sale: 650,
  },
  {
    id: 7,
    title: "Rainbow Jacquard Sweater for Women",
    image: "/img/products/electronic-fabric/13.jpg",
    price: 400,
    originalPrice: 450,
    discount: 50,
    review: 300,
    sale: 5000,
  },
  {
    id: 8,
    title: "Bluetooth Wireless 5.0 Smart Watch",
    image: "/img/products/electronic-fabric/10.jpg",
    price: 350,
    originalPrice: 400,
    discount: 40,
    review: 200,
    sale: 400,
  },
  {
    id: 9,
    title: "Apple 2022 Macbook Pro 18GB 256GB Laptop",
    image: "/img/products/electronic-fabric/11.jpg",
    price: 250,
    originalPrice: 300,
    discount: 80,
    review: 300,
    sale: 400,
  },
  {
    id: 10,
    title: "Women Sweaters Autumn Winter Tops Slim Women",
    image: "/img/products/electronic-fabric/12.jpg",
    price: 150,
    originalPrice: 200,
    discount: 30,
    review: 250,
    sale: 600,
  },
];

const newProducts = [
  {
    id: 1,
    title: "Men's Orange Black White Print Summer Sweater",
    image: "/img/products/electronic-fabric/9.jpg",
    price: 150,
    originalPrice: 200,
    discount: 20,
    review: 50,
    sale: 200,
  },
  {
    id: 2,
    title: "Rainbow Jacquard Sweater for Women",
    image: "/img/products/electronic-fabric/13.jpg",
    price: 350,
    originalPrice: 400,
    discount: 50,
    review: 100,
    sale: 350,
  },
  {
    id: 3,
    title: "Bluetooth Wireless 5.0 Smart Watch",
    image: "/img/products/electronic-fabric/10.jpg",
    price: 250,
    originalPrice: 300,
    discount: 60,
    review: 350,
    sale: 1000,
  },
  {
    id: 4,
    title: "Apple 2022 Macbook Pro 18GB 256GB Laptop",
    image: "/img/products/electronic-fabric/4.jpg",
    price: 300,
    originalPrice: 360,
    discount: 40,
    review: 200,
    sale: 300,
  },
  {
    id: 5,
    title: "Women Sweaters Autumn Winter Tops Slim Women",
    image: "/img/products/electronic-fabric/12.jpg",
    price: 200,
    originalPrice: 250,
    discount: 50,
    review: 400,
    sale: 1000,
  },
  {
    id: 6,
    title: "Multicolor Rainbow Jacquard Sweater for Women",
    image: "/img/products/electronic-fabric/14.jpg",
    price: 150,
    originalPrice: 200,
    discount: 70,
    review: 200,
    sale: 650,
  },
  {
    id: 7,
    title: "Rainbow Jacquard Sweater for Women",
    image: "/img/products/electronic-fabric/13.jpg",
    price: 400,
    originalPrice: 450,
    discount: 50,
    review: 300,
    sale: 5000,
  },
  {
    id: 8,
    title: "Bluetooth Wireless 5.0 Smart Watch",
    image: "/img/products/electronic-fabric/10.jpg",
    price: 350,
    originalPrice: 400,
    discount: 40,
    review: 200,
    sale: 400,
  },
  {
    id: 9,
    title: "Apple 2022 Macbook Pro 18GB 256GB Laptop",
    image: "/img/products/electronic-fabric/11.jpg",
    price: 250,
    originalPrice: 300,
    discount: 80,
    review: 300,
    sale: 400,
  },
  {
    id: 10,
    title: "Women Sweaters Autumn Winter Tops Slim Women",
    image: "/img/products/electronic-fabric/12.jpg",
    price: 150,
    originalPrice: 200,
    discount: 30,
    review: 250,
    sale: 600,
  },
];

const featureProductSlider = [
  {
    id: 1,
    title: "Men's Orange Black White Print Summer Sweater",
    image: "/img/products/shop/4.jpg",
    price: 150,
    originalPrice: 200,
    discount: 20,
    review: 50,
    sale: 200,
  },
  {
    id: 2,
    title: "Rainbow Jacquard Sweater for Women",
    image: "/img/products/shop/5.jpg",
    price: 350,
    originalPrice: 400,
    discount: 50,
    review: 100,
    sale: 350,
  },
  {
    id: 3,
    title: "Bluetooth Wireless 5.0 Smart Watch",
    image: "/img/products/shop/6.jpg",
    price: 250,
    originalPrice: 300,
    discount: 60,
    review: 350,
    sale: 1000,
  },
  {
    id: 4,
    title: "Apple 2022 Macbook Pro 18GB 256GB Laptop",
    image: "/img/products/shop/7.jpg",
    price: 300,
    originalPrice: 360,
    discount: 40,
    review: 200,
    sale: 300,
  },
  {
    id: 5,
    title: "Women Sweaters Autumn Winter Tops Slim Women",
    image: "/img/products/shop/8.jpg",
    price: 200,
    originalPrice: 250,
    discount: 50,
    review: 400,
    sale: 1000,
  },
  {
    id: 6,
    title: "Multicolor Rainbow Jacquard Sweater for Women",
    image: "/img/products/shop/9.jpg",
    price: 150,
    originalPrice: 200,
    discount: 70,
    review: 200,
    sale: 650,
  },
  {
    id: 7,
    title: "Rainbow Jacquard Sweater for Women",
    image: "/img/products/shop/10.jpg",
    price: 400,
    originalPrice: 450,
    discount: 50,
    review: 300,
    sale: 5000,
  },
  {
    id: 8,
    title: "Bluetooth Wireless 5.0 Smart Watch",
    image: "/img/products/shop/11.jpg",
    price: 350,
    originalPrice: 400,
    discount: 40,
    review: 200,
    sale: 400,
  },
  {
    id: 9,
    title: "Apple 2022 Macbook Pro 18GB 256GB Laptop",
    image: "/img/products/shop/13.jpg",
    price: 250,
    originalPrice: 300,
    discount: 80,
    review: 300,
    sale: 400,
  },
  {
    id: 10,
    title: "Women Sweaters Autumn Winter Tops Slim Women",
    image: "/img/products/shop/12.jpg",
    price: 150,
    originalPrice: 200,
    discount: 30,
    review: 250,
    sale: 600,
  },
];

const weeklyBestSellerSlider = [
  {
    id: 1,
    title: "OCN Store",
    image: "/img/vendor-bg/2.jpg",
    logo: "/img/vendor/2.png",
    price: 150,
    originalPrice: 200,
    discount: 20,
    review: 50,
    product: 2000,
  },
  {
    id: 2,
    title: "Nissan Global",
    image: "/img/vendor-bg/3.jpg",
    logo: "/img/vendor/3.png",
    price: 350,
    originalPrice: 400,
    discount: 50,
    review: 100,
    product: 3500,
  },
  {
    id: 3,
    title: "Card Discount Store",
    image: "/img/vendor-bg/4.jpg",
    logo: "/img/vendor/4.png",
    price: 250,
    originalPrice: 300,
    discount: 60,
    review: 350,
    product: 1000,
  },
  {
    id: 4,
    title: "Adidas Store",
    image: "/img/vendor-bg/5.jpg",
    logo: "/img/vendor/5.png",
    price: 300,
    originalPrice: 360,
    discount: 40,
    review: 200,
    product: 30000,
  },
  {
    id: 5,
    title: "H&M Brand",
    logo: "/img/vendor-bg/6.jpg",
    image: "/img/vendor/6.png",
    price: 200,
    originalPrice: 250,
    discount: 50,
    review: 400,
    product: 1500,
  },
  {
    id: 6,
    title: "Veolia Shoe",
    image: "/img/vendor-bg/7.jpg",
    logo: "/img/vendor/7.png",
    price: 150,
    originalPrice: 200,
    discount: 70,
    review: 200,
    product: 6500,
  },
  {
    id: 7,
    title: "Nissan Group",
    image: "/img/vendor-bg/8.jpg",
    logo: "/img/vendor/8.png",
    price: 400,
    originalPrice: 450,
    discount: 50,
    review: 300,
    product: 5000,
  },
  {
    id: 8,
    title: "Levis",
    image: "/img/vendor-bg/9.jpg",
    logo: "/img/vendor/9.png",
    price: 350,
    originalPrice: 400,
    discount: 40,
    review: 200,
    product: 4000,
  },
  {
    id: 9,
    title: "Lasy Online Store",
    image: "/img/vendor-bg/10.jpg",
    logo: "/img/vendor/10.png",
    price: 250,
    originalPrice: 300,
    discount: 80,
    review: 300,
    product: 3600,
  },
  {
    id: 10,
    title: "Ebay Online",
    image: "/img/vendor-bg/11.jpg",
    logo: "/img/vendor/11.png",
    price: 150,
    originalPrice: 200,
    discount: 30,
    review: 250,
    product: 6000,
  },
];

const topBrandSlider = [
  {
    id: 1,
    title: "PatPat",
    image: "/img/brands/1.png",
    quantity: 15,
  },
  {
    id: 2,
    title: "Wilson",
    image: "/img/brands/2.png",
    quantity: 250,
  },
  {
    id: 3,
    title: "Lenovo",
    image: "/img/brands/3.png",
    quantity: 535,
  },
  {
    id: 4,
    title: "Suzuki",
    image: "/img/brands/4.png",
    quantity: 215,
  },
  {
    id: 5,
    title: "Nokia",
    image: "/img/brands/5.png",
    quantity: 231,
  },
  {
    id: 6,
    title: "Levis",
    image: "/img/brands/6.png",
    quantity: 215,
  },
  {
    id: 7,
    title: "Canon",
    image: "/img/brands/7.png",
    quantity: 555,
  },
  {
    id: 8,
    title: "Philips",
    image: "/img/brands/8.png",
    quantity: 450,
  },
  {
    id: 9,
    title: "Yamaha",
    image: "/img/brands/9.png",
    quantity: 55,
  },
  {
    id: 10,
    title: "Booking.com",
    image: "/img/brands/10.png",
    quantity: 20,
  },
  {
    id: 11,
    title: "Logitech",
    image: "/img/brands/11.png",
    quantity: 535,
  },
  {
    id: 12,
    title: "CocaCola",
    image: "/img/brands/12.png",
    quantity: 145,
  },
  {
    id: 13,
    title: "Sony",
    image: "/img/brands/13.png",
    quantity: 145,
  },
  {
    id: 14,
    title: "Adidas",
    image: "/img/brands/14.png",
    quantity: 150,
  },
  {
    id: 15,
    title: "Lotto",
    image: "/img/brands/15.png",
    quantity: 250,
  },
  {
    id: 16,
    title: "Asus",
    image: "/img/brands/16.png",
    quantity: 450,
  },
  {
    id: 17,
    title: "PatPat",
    image: "/img/brands/17.png",
    quantity: 345,
  },
];
export {
  topCategory,
  discountSliderProducts,
  flashSaleSliderProducts,
  newProducts,
  featureProductSlider,
  weeklyBestSellerSlider,
  topBrandSlider,
  blogGrideData,
  navigation,
  userNavigation,
  categorys,
};
