export const allProducts = [
  {
    prices: {
      originalPrice: 666,
      price: 663,
      discount: 0.45045045045045046,
    },
    _id: "6735e9b0da6ef8ce9949aebb",
    productId: "6735e9b0da6ef8ce9949aebb",
    sku: "fsadfs",
    barcode: "afsaf66",
    name: "GUSTO Sliced Calabrese Salami, 4 OZ",
    description:
      "<p>GUSTO Sliced Calabrese Salami is a premium cured meat crafted with traditional Italian methods. Made from high-quality pork, this salami is seasoned with a bold blend of spices, including paprika and chili, to deliver its signature mildly spicy and smoky flavor. The Calabrese style, originating from the Calabria region of Italy, is known for its rich, savory taste with a hint of heat.</p><p><strong>Key Features:</strong></p><ul><li><strong>Weight:</strong> 4 ounces of pre-sliced salami for convenience.</li><li><strong>Flavor Profile:</strong> Spicy and smoky with a balanced savory depth.</li><li><strong>Texture:</strong> Firm yet tender slices, perfect for pairing.</li><li><strong>Uses:</strong> Ideal for charcuterie boards, sandwiches, pizzas, or as a flavorful snack.</li><li><strong>Preservation:</strong> Vacuum-sealed for freshness.</li></ul><p>Whether you’re hosting a gathering or indulging in a gourmet treat, GUSTO Sliced Calabrese Salami offers an authentic taste of Italy in every bite</p>",
    slug: "gusto-sliced-calabrese-salami-4-oz",
    brand: "Nexover",
    category: "Meat & Fish",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731586570/grostore/81hZJKbV3aL._AC_SX679_.jpg",
    ],
    stock: 132,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T12:14:40.447Z",
    updatedAt: "2024-12-09T10:06:47.879Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 555,
      price: 555,
      discount: 0,
    },
    _id: "6735e96eda6ef8ce9949ae5f",
    productId: "6735e96eda6ef8ce9949ae5f",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Creminelli - Italian Artisan Handcrafted Fine Meats, Sliced Prosciutto Salami, 2.0 Ounce",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "creminelli-italian-artisan-handcrafted-fine-meats-sliced-prosciutto-salami-2-0-ounce",
    brand: "Nexover",
    category: "Meat & Fish",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731586662/grostore/61%2BlKJDCGML._AC_UL320_.jpg",
    ],
    stock: 55,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T12:13:34.165Z",
    updatedAt: "2024-12-09T10:20:46.289Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 333,
      price: 333,
      discount: 0,
    },
    _id: "6735e895da6ef8ce9949ae03",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Malt-O-Meal Tootie Fruities Marshmallow Cereal, Fruity Breakfast Cereal with Marshmallows, Large Cereal for Family, 30 OZ Resealable Cereal Bag",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "malt-o-meal-tootie-fruities-marshmallow-cereal-fruity-breakfast-cereal-with-marshmallows-large-cereal-for-family-30-oz-resealable-cereal-bag",
    brand: "Bird Wings",
    category: "Breakfast",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731586183/grostore/71Xe9%2BcGuSL._SX679_.jpg",
    ],
    stock: 33,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T12:09:57.505Z",
    updatedAt: "2024-12-09T10:20:05.707Z",
    __v: 0,
    productId: "6735e895da6ef8ce9949ae03",
  },
  {
    prices: {
      originalPrice: 889,
      price: 800,
      discount: 10.011248593925758,
    },
    _id: "6735e870da6ef8ce9949adef",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Malt-O-Meal Fruity Dyno Bites Cereal, Gluten Free Breakfast Cereal with Fruity Flavor, Large Cereal for Family, 61 OZ Resealable Cereal Bag",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "malt-o-meal-fruity-dyno-bites-cereal-gluten-free-breakfast-cereal-with-fruity-flavor-large-cereal-for-family-61-oz-resealable-cereal-bag",
    brand: "Nexover",
    category: "Breakfast",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731586138/grostore/71MvTp4p3rL._SX679_.jpg",
    ],
    stock: 44,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T12:09:20.621Z",
    updatedAt: "2024-12-09T10:21:04.119Z",
    __v: 0,
    productId: "6735e870da6ef8ce9949adef",
  },
  {
    prices: {
      originalPrice: 333,
      price: 300,
      discount: 9.90990990990991,
    },
    _id: "6735e7adda6ef8ce9949ad93",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "365 by Whole Foods Market, Organic Dried Sweetened",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "365-by-whole-foods-market-organic-dried-sweetened",
    brand: "Bird Wings",
    category: "Fresh Organic",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731585945/grostore/51uPxCAQV4L._SX679_.jpg",
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729156320/grostore/itXzsN5z4mRcQOvxl3qwWdPUo6UFBR7JYgnHNCaP.png",
    ],
    stock: 22,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T12:06:05.041Z",
    updatedAt: "2024-12-09T10:21:12.070Z",
    __v: 0,
    productId: "6735e7adda6ef8ce9949ad93",
  },
  {
    prices: {
      originalPrice: 444,
      price: 444,
      discount: 0,
    },
    _id: "6735e755da6ef8ce9949ad37",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Cocofresha Pulling Oil,",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "cocofresha-pulling-oil-",
    brand: "Bird Wings",
    category: "Fresh Organic",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731585699/grostore/71%2B2P8QnZbL._AC_SX679_.jpg",
    ],
    stock: 33,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T12:04:37.741Z",
    updatedAt: "2024-12-09T10:21:18.955Z",
    __v: 0,
    productId: "6735e755da6ef8ce9949ad37",
  },
  {
    prices: {
      originalPrice: 222,
      price: 222,
      discount: 0,
    },
    _id: "6735e64fda6ef8ce9949ad23",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Fresh Tropical Gold Hawaiian Pineapples (2 ea)",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "fresh-tropical-gold-hawaiian-pineapples-2-ea-",
    brand: "Bird Wings",
    category: "Fresh Organic",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731585603/grostore/31QtUPyu7OL._QL70_FMwebp_.webp",
    ],
    stock: 0,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T12:00:15.277Z",
    updatedAt: "2024-12-09T10:21:27.668Z",
    __v: 0,
    productId: "6735e64fda6ef8ce9949ad23",
  },
  {
    prices: {
      originalPrice: 600,
      price: 500,
      discount: 16.666666666666664,
    },
    _id: "6735e5afda6ef8ce9949acb5",
    productId: "6735e5afda6ef8ce9949acb5",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Stir it Up Bundle",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "-stir-it-up-bundle",
    brand: "Bird Wings",
    category: "Vegetables",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731585436/grostore/51f3QHk8-FL._SY300_SX300_QL70_FMwebp_.webp",
    ],
    stock: 88,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T11:57:36.005Z",
    updatedAt: "2024-12-09T10:21:34.006Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 700,
      price: 700,
      discount: 0,
    },
    _id: "6735e544da6ef8ce9949ac47",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Nasal Aspirator for Baby,Large Flow Electric Nose Suction for Baby,Relieves Nasal Congestion,Baby Nose Sucker",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "nasal-aspirator-for-baby-large-flow-electric-nose-suction-for-baby-relieves-nasal-congestion-baby-nose-sucker",
    brand: "Biofuel",
    category: "Baby Care",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731585328/grostore/61M006S8kqL._AC_SX679_%281%29.jpg",
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731584025/grostore/313LIPTE%2BrL._SY300_SX300_.jpg",
    ],
    stock: 88,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T11:55:48.865Z",
    updatedAt: "2024-12-09T10:21:44.696Z",
    __v: 0,
    productId: "6735e544da6ef8ce9949ac47",
  },
  {
    prices: {
      originalPrice: 800,
      price: 800,
      discount: 0,
    },
    _id: "6735e0b5da6ef8ce9949ac33",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Angelcare Baby Bath Support (Gray) | Ideal for Babies Less Than 6 Months Old",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "angelcare-baby-bath-support-gray-ideal-for-babies-less-than-6-months-old",
    brand: "Biofuel",
    category: "Baby Care",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731584162/grostore/61x79D9WpNL._SX466_.jpg",
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729150097/grostore/yHoald7x3oEhVOHSJ29JIIEW2b5hOuE4C6JuJvpE%281%29.png",
    ],
    stock: 88,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T11:36:21.450Z",
    updatedAt: "2024-12-09T10:21:53.965Z",
    __v: 0,
    productId: "6735e0b5da6ef8ce9949ac33",
  },
  {
    prices: {
      originalPrice: 900,
      price: 900,
      discount: 0,
    },
    _id: "6735e033da6ef8ce9949abd7",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Baby Dove Derma Care Soothing Wash Skin Care with Colloidal",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "baby-dove-derma-care-soothing-wash-skin-care-with-colloidal",
    brand: "Biofuel",
    category: "Baby Care",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731584025/grostore/313LIPTE%2BrL._SY300_SX300_.jpg",
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729149954/grostore/gYZb2Q60Y57JTo2BuS7Fh41XtCk530HBkJ3QwHp6.png",
    ],
    stock: 33,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-14T11:34:11.823Z",
    updatedAt: "2024-12-09T10:22:15.675Z",
    __v: 0,
    productId: "6735e033da6ef8ce9949abd7",
  },
  {
    prices: {
      originalPrice: 332,
      price: 222,
      discount: 33.13253012048193,
    },
    _id: "6733280a7aa089fed07a6071",
    productId: "6733280a7aa089fed07a6071",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Fresh Milk · Spain",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "fresh-milk-spain",
    brand: "Biofuel",
    category: "Clod Drinks",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731405812/grostore/lUY5cNja5BAO5SAttEcgr9Ab03uqh7Hdv5UBth8G%281%29.png",
    ],
    stock: 444,
    flashSale: true,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [
      {
        user: "6729db0dea19e02ae487bdfb",
        productId: "6733280a7aa089fed07a6071",
        name: "HASAN",
        rating: 2,
        comment: "rdyrfyrdc",
        reviewDate: "2024-11-20T04:57:58.651Z",
        _id: "673d6c56d9ed13b6b8adfe20",
      },
    ],
    averageRating: 2,
    createdAt: "2024-11-12T10:03:54.106Z",
    updatedAt: "2024-12-09T10:23:01.643Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 33,
      price: 33,
      discount: 0,
    },
    _id: "673327c54816347fb369a61b",
    productId: "673327c54816347fb369a61b",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Raw Turkey Drumsticks Full Length Food",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "raw-turkey-drumsticks-full-length-food",
    brand: "Biofuel",
    category: "Meat & Fish",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729155850/grostore/S42WBq4WDjzkDDNWlXpW1Ji1fzy9eOvs37HpWQ82.png",
    ],
    stock: 33,
    flashSale: true,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [
      {
        user: "6729db0dea19e02ae487bdfb",
        productId: "673327c54816347fb369a61b",
        name: "HASAN",
        rating: 5,
        comment: "Good product",
        reviewDate: "2024-11-14T10:56:22.415Z",
        _id: "6735d756da6ef8ce9949a8e9",
      },
    ],
    averageRating: 5,
    createdAt: "2024-11-12T10:02:45.147Z",
    updatedAt: "2024-12-09T10:23:13.667Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 44,
      price: 44,
      discount: 0,
    },
    _id: "673327894816347fb369a618",
    productId: "673327894816347fb369a618",
    sku: "fsadfs",
    barcode: "33",
    name: "Fish Gilt-head bream ",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "fish-gilt-head-bream-",
    brand: "Bird Wings",
    category: "Meat & Fish",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729155600/grostore/YsOnz83mF4VNISkIIAfbVf1azYs1YTvniM7p6tTW.png",
    ],
    stock: 44,
    flashSale: true,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [
      {
        user: "6729db0dea19e02ae487bdfb",
        productId: "673327894816347fb369a618",
        name: "HASAN",
        rating: 5,
        comment: "good product",
        reviewDate: "2024-11-14T10:56:11.952Z",
        _id: "6735d74bda6ef8ce9949a8df",
      },
    ],
    averageRating: 5,
    createdAt: "2024-11-12T10:01:45.953Z",
    updatedAt: "2024-12-09T10:23:22.863Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 33,
      price: 33,
      discount: 0,
    },
    _id: "673327447aa089fed07a606d",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "  Similac Similac Neosure Powder Infant",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "-similac-similac-neosure-powder-infant",
    brand: "Bird Wings",
    category: "Breakfast",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729156538/grostore/hkFbO8OEBfIrOk0yGNhDSMe3MvXCwNZwXnEAkrbj%281%29.png",
    ],
    stock: 22,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [
      {
        user: "6729db0dea19e02ae487bdfb",
        productId: "673327447aa089fed07a606d",
        name: "HASAN",
        rating: 3,
        comment: "good",
        reviewDate: "2024-11-14T10:55:47.248Z",
        _id: "6735d733da6ef8ce9949a8d2",
      },
    ],
    averageRating: 3,
    createdAt: "2024-11-12T10:00:36.230Z",
    updatedAt: "2024-12-09T10:23:30.656Z",
    __v: 0,
    productId: "673327447aa089fed07a606d",
  },
  {
    prices: {
      originalPrice: 88,
      price: 88,
      discount: 0,
    },
    _id: "67332692f9039c34ebabde6b",
    productId: "67332692f9039c34ebabde6b",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Felli On the Go Yogurt Parfait Snack ",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "felli-on-the-go-yogurt-parfait-snack-cup-with-lid-100-leak-proof-spoon-granola-holder-for",
    brand: "Nexover",
    category: "Breakfast",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729149788/grostore/kcAUkZadr6IwjevpF6922njgGl76Ov0tX8PIh1if.png",
    ],
    stock: 88,
    flashSale: true,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [
      {
        user: "6729db0dea19e02ae487bdfb",
        productId: "67332692f9039c34ebabde6b",
        name: "HASAN",
        rating: 5,
        comment: "very good product",
        reviewDate: "2024-11-14T10:55:03.601Z",
        _id: "6735d707da6ef8ce9949a8cc",
      },
    ],
    averageRating: 5,
    createdAt: "2024-11-12T09:57:38.131Z",
    updatedAt: "2024-12-09T10:23:37.669Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 332,
      price: 332,
      discount: 0,
    },
    _id: "67332653f9039c34ebabde68",
    sku: "adfa",
    barcode: "asdf",
    name: "Sistema To Go Collection Breakfast Plastic",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "sistema-to-go-collection-breakfast-plastic",
    brand: "Nexover",
    category: "Breakfast",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731405383/grostore/81L9bh%2BEtSL._AC_SX679_.jpg",
    ],
    stock: 2,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [
      {
        user: "6729db0dea19e02ae487bdfb",
        productId: "67332653f9039c34ebabde68",
        name: "HASAN",
        rating: 5,
        comment: "Very good product",
        reviewDate: "2024-11-14T06:29:20.315Z",
        _id: "673598c0da6ef8ce99499af3",
      },
    ],
    averageRating: 5,
    createdAt: "2024-11-12T09:56:35.269Z",
    updatedAt: "2024-12-09T10:24:54.717Z",
    __v: 0,
    productId: "67332653f9039c34ebabde68",
  },
  {
    prices: {
      originalPrice: 345,
      price: 345,
      discount: 0,
    },
    _id: "673325464816347fb369a60e",
    sku: "sasdf",
    barcode: "asdfasf",
    name: "12 Organic California Hass Avocado",
    description: "12 Organic California Hass Avocado",
    slug: "12-organic-california-hass-avocado",
    brand: "Nexover",
    category: "Fresh Organic",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731405109/grostore/51QEFmnhZRL.jpg",
    ],
    stock: 33,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:52:06.652Z",
    updatedAt: "2024-11-12T09:52:06.652Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 777,
      price: 777,
      discount: 0,
    },
    _id: "67332484f9039c34ebabde60",
    productId: "67332484f9039c34ebabde60",
    sku: "dghd",
    barcode: "sdfgs",
    name: "Fresh Organic Grape Tomatoes",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "fresh-organic-grape-tomatoes",
    brand: "Nexover",
    category: "Fresh Organic",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731405001/grostore/81vlIooKjuL._SX679_.jpg",
    ],
    stock: 77,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [
      {
        user: "6729db0dea19e02ae487bdfb",
        productId: "67332484f9039c34ebabde60",
        name: "HASAN",
        rating: 5,
        comment: "good product",
        reviewDate: "2024-11-14T11:23:58.263Z",
        _id: "6735ddceda6ef8ce9949ab3f",
      },
    ],
    averageRating: 5,
    createdAt: "2024-11-12T09:48:52.668Z",
    updatedAt: "2024-12-09T10:25:00.087Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 33,
      price: 22,
      discount: 33.33333333333333,
    },
    _id: "673324023b69517f7d3397cb",
    productId: "673324023b69517f7d3397cb",
    sku: "afda",
    barcode: "asdfas",
    name: "Glow Reviver Lip Oil",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "22",
    brand: "Nexover",
    category: "Beauty & Health",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731404783/grostore/61vKMD8VMFL._SX466_.jpg",
    ],
    stock: 22,
    flashSale: true,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:46:42.592Z",
    updatedAt: "2024-12-09T10:25:05.134Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 232,
      price: 222,
      discount: 4.310344827586207,
    },
    _id: "673323b6f9039c34ebabde5a",
    sku: "asda",
    barcode: "asdfas",
    name: "Beauty of Joseon Revive Eye Serum",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "beauty-of-joseon-revive-eye-serum",
    brand: "Nexover",
    category: "Beauty & Health",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731404716/grostore/61li%2Bq2pbqL._SX466_%281%29.jpg",
    ],
    stock: 0,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:45:26.413Z",
    updatedAt: "2024-12-09T10:25:15.342Z",
    __v: 0,
    productId: "673323b6f9039c34ebabde5a",
  },
  {
    prices: {
      originalPrice: 22,
      price: 11,
      discount: 50,
    },
    _id: "673322f6f9039c34ebabde57",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Johnson's Baby",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "johnson-s-baby",
    brand: "simplegraph",
    category: "Baby Care",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729149955/grostore/InLLpWyxtMXDMNBTtG8f6QXyAXIzqK43Hp0X4WFJ.png",
    ],
    stock: 0,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:42:14.910Z",
    updatedAt: "2024-12-09T10:25:20.957Z",
    __v: 0,
    productId: "673322f6f9039c34ebabde57",
  },
  {
    prices: {
      originalPrice: 22,
      price: 21,
      discount: 4.545454545454546,
    },
    _id: "67332276e856bb5cd7ee9048",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Baby Bath Towel",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "baby-bath-towel",
    brand: "simplegraph",
    category: "Baby Care",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731404393/grostore/2LjiaifbvJ1Rd4b0dl2Ey2VZCgyLGnk9WYGvSaBk.png",
    ],
    stock: 11,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:40:06.995Z",
    updatedAt: "2024-12-09T10:25:26.213Z",
    __v: 0,
    productId: "67332276e856bb5cd7ee9048",
  },
  {
    prices: {
      originalPrice: 33,
      price: 30,
      discount: 9.090909090909092,
    },
    _id: "67331fbde47736e9375cd473",
    productId: "67331fbde47736e9375cd473",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Gunter's Pure Clover Honey Bears - 12 oz (Pack of 6)",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "gunter-s-pure-clover-honey-bears-12-oz-pack-of-6-",
    brand: "simplegraph",
    category: "Honey",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729141937/grostore/RambutanSweetDeliciousFruit.png",
    ],
    stock: 33,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:28:29.304Z",
    updatedAt: "2024-12-09T10:25:35.613Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 456,
      price: 444,
      discount: 2.631578947368421,
    },
    _id: "67331e506200b5ea638187f8",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Pomegranate Fruit Peach",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "pomegranate-fruit-peach",
    brand: "simplegraph",
    category: "Fresh Fruits",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729155965/grostore/QRrqV5dcT0zLMPR7wNbRGGkSk9f16V3amjaKk4R8.png",
    ],
    stock: 44,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:22:24.397Z",
    updatedAt: "2024-12-09T10:25:55.874Z",
    __v: 0,
    productId: "67331e506200b5ea638187f8",
  },
  {
    prices: {
      originalPrice: 234,
      price: 234,
      discount: 0,
    },
    _id: "67331dc56200b5ea638187f5",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Dragon Fruit",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "dragon-fruit",
    brand: "simplegraph",
    category: "Fresh Fruits",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729156320/grostore/itXzsN5z4mRcQOvxl3qwWdPUo6UFBR7JYgnHNCaP.png",
    ],
    stock: 22,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:20:05.538Z",
    updatedAt: "2024-12-09T10:26:01.853Z",
    __v: 0,
    productId: "67331dc56200b5ea638187f5",
  },
  {
    prices: {
      originalPrice: 78,
      price: 78,
      discount: 0,
    },
    _id: "67331d59e47736e9375cd46f",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Kashmir Apples",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "kashmir-apples",
    brand: "simplegraph",
    category: "Fresh Fruits",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729143910/grostore/51v67fLxK6L._SX679_.jpg",
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729143910/grostore/51omK%2B5VIWL._SX679_.jpg",
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729143910/grostore/51%2BJjHS-5nL._SX679_.jpg",
    ],
    stock: 77,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:18:17.324Z",
    updatedAt: "2024-12-09T10:26:10.322Z",
    __v: 0,
    productId: "67331d59e47736e9375cd46f",
  },
  {
    prices: {
      originalPrice: 333,
      price: 222,
      discount: 33.33333333333333,
    },
    _id: "67331cdce47736e9375cd46c",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Fresh Bananas",
    description:
      "Sweet, creamy, and packed with energy—our fresh bananas are the perfect snack for any time of day! Grown in tropical regions and picked at peak ripeness, these bananas offer a natural sweetness and smooth texture that everyone loves. Whether you enjoy them on their own, in smoothies, or as part of your favorite desserts, our premium bananas are a delicious and nutritious addition to your diet.",
    slug: "fresh-bananas",
    brand: "Color Love",
    category: "Fresh Fruits",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729144178/grostore/61mwWhBFZiL._SY466_.jpg",
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729144178/grostore/31CaI8UzPtL._SX679_.jpg",
    ],
    stock: 22,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:16:12.782Z",
    updatedAt: "2024-11-12T09:16:12.782Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 666,
      price: 555,
      discount: 16.666666666666664,
    },
    _id: "67331c77e47736e9375cd469",
    productId: "67331c77e47736e9375cd469",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Broccoli Cabbage",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "broccoli-cabbage",
    brand: "Color Love",
    category: "Vegetables",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729156887/grostore/HaH5vkqPOmi15yPd9x9Qho94kyl7Qm0fAleDsOMV.png",
    ],
    stock: 110,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [
      {
        user: "6729db0dea19e02ae487bdfb",
        productId: "67331c77e47736e9375cd469",
        name: "HASAN",
        rating: 4,
        comment: "Very good product",
        reviewDate: "2024-11-14T10:54:51.943Z",
        _id: "6735d6fbda6ef8ce9949a8c5",
      },
    ],
    averageRating: 4,
    createdAt: "2024-11-12T09:14:31.565Z",
    updatedAt: "2024-12-09T10:26:21.105Z",
    __v: 0,
  },
  {
    prices: {
      originalPrice: 444,
      price: 400,
      discount: 9.90990990990991,
    },
    _id: "67331c2a963f976627cc3c65",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Fresh Onions",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "fresh-onions",
    brand: "Color Love",
    category: "Vegetables",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1731402779/grostore/DI69pQUQm5pdEnREfRD0Hj42g46ZqmfVePCDWlsB.png",
    ],
    stock: 33,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:13:14.893Z",
    updatedAt: "2024-12-09T10:26:27.726Z",
    __v: 0,
    productId: "67331c2a963f976627cc3c65",
  },
  {
    prices: {
      originalPrice: 222,
      price: 200,
      discount: 9.90990990990991,
    },
    _id: "67331bdee47736e9375cd466",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Fresh Capsicum (Bell Pepper)",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "fresh-capsicum-bell-pepper-",
    brand: "Color Love",
    category: "Vegetables",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729143559/grostore/capsicum2.jpg",
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729143559/grostore/capsicum3.jpg",
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729143559/grostore/capsicum4.jpg",
    ],
    stock: 22,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [],
    averageRating: 0,
    createdAt: "2024-11-12T09:11:58.227Z",
    updatedAt: "2024-12-09T10:26:59.707Z",
    __v: 0,
    productId: "67331bdee47736e9375cd466",
  },
  {
    prices: {
      originalPrice: 123,
      price: 123,
      discount: 0,
    },
    _id: "67331b7be47736e9375cd463",
    sku: "fsadfs",
    barcode: "afsaf",
    name: "Fress Ginger",
    description:
      "<p>We are offering Premium Rui With means This fishes are 100% dish bread and specially collected from Rajshahi.</p><p>Our RUI fish are mentioned as Medium size with means each of the live fish will have to be between 1.8 KG to 2.5 KG.</p><p>Bengali cut pieces of Freshwater Rui that's caught fresh, cut, cleaned.</p><p>These are Medium pieces of Bengali Cuts of freshwater Rui, that are perfect for curries or fish fry. Rui is a soft-textured bony fish with a subtle flavour.</p><p>Chaldal fish &amp; seafood is sourced from approved local fishermen Regularly, they contain no added chemicals.</p><p>Features of our premium Rui fish:</p><p>1. 100% native cotton fish.</p><p>2. Our fishes are sourced from selected fish farms in Rajshahi where systematic fish farming is ensured.</p><p>3. Our premium fish are processed under our own supervision by skilled artisans.</p><p>4. Clean water is used when poaching premium fish.</p><p>5. Safe packing is done in compliance with complete hygiene rules.</p><p>6. Fish are caught and processed on the same day.</p>",
    slug: "ada",
    brand: "Color Love",
    category: "Vegetables",
    videoUrl: "https://www.youtube.com/watch?v=F0lowv3DyfI",
    image: [
      "https://res.cloudinary.com/dmadhbgty/image/upload/v1729156171/grostore/0RrfWX0cXUZyqSbbsDlSVNl7zGz6lsyktanugrH1.png",
    ],
    stock: 11,
    flashSale: false,
    tag: ["[]"],
    variants: [],
    isCombination: false,
    status: "show",
    ratings: [
      {
        user: "6729db0dea19e02ae487bdfb",
        productId: "67331b7be47736e9375cd463",
        name: "HASAN",
        rating: 1,
        comment: "aldfkjasfa",
        reviewDate: "2024-11-14T06:19:20.426Z",
        _id: "67359668da6ef8ce99499a7c",
      },
    ],
    averageRating: 1,
    createdAt: "2024-11-12T09:10:19.272Z",
    updatedAt: "2024-12-09T10:26:52.477Z",
    __v: 0,
    productId: "67331b7be47736e9375cd463",
  },
];
